// This file was generated by Prisma.
// dotenv import removed — env vars are set by the deployment platform.
// For local development, set DATABASE_URL in your shell or use a .env loader externally.
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
